/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    DaBreadcrumbs: typeof import('./src/components/reus/DaBreadcrumbs.vue')['default']
    DaSpinner: typeof import('./src/components/reus/DaSpinner.vue')['default']
    DaTable: typeof import('./src/components/reus/DaTable.vue')['default']
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    DFlex: typeof import('./src/components/reus/html-containers/DFlex.vue')['default']
    DSpin: typeof import('./src/components/reus/DSpin.vue')['default']
    DTableDrawer: typeof import('./src/components/reus/DTableDrawer.vue')['default']
    DTableHref: typeof import('./src/components/reus/DTableHref.vue')['default']
    DText: typeof import('./src/components/reus/texts/DText.vue')['default']
    MainSubLinks: typeof import('./src/components/single-use/MainSubLinks.vue')['default']
    PageSample: typeof import('./src/components/samples/PageSample.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/single-use/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/single-use/TheHeader.vue')['default']
    TheMainNav: typeof import('./src/components/single-use/TheMainNav.vue')['default']
    UserInfo: typeof import('./src/components/single-use/UserInfo.vue')['default']
    YandMap: typeof import('./src/components/reus/YandMap.vue')['default']
  }
}
