export const adminTableColumns = [
    {
        title: 'EmUID',
        dataIndex: 'EmUID',
        key: 'EmUID',
        align: 'center',
        ellipsis: true,
        width: 150,
    },
    {
        title: 'IIN',
        dataIndex: 'IIN',
        key: 'IIN',
        align: 'center',
        ellipsis: true,
        width: 150,
    },
    {
        title: 'FIO',
        dataIndex: 'FIO',
        key: 'FIO',
        align: 'center',
        ellipsis: true,
    },
    {
        title: 'Phone',
        dataIndex: 'LOGIN',
        key: 'LOGIN',
        align: 'center',
        ellipsis: true,
        width: 150,
    },
    {
        title: 'Status',
        dataIndex: 'Valid',
        key: 'Valid',
        align: 'center',
        ellipsis: true,
        width: 80,
    },
    {
        title: 'Role',
        dataIndex: 'Role',
        key: 'Role',
        align: 'center',
        ellipsis: true,
        width: 70,
    },
    {
        title: 'REG_ID',
        dataIndex: 'REG_ID',
        key: 'REG_ID',
        align: 'center',
        ellipsis: true,
        width: 150,
    },
    {
        title: 'BIN',
        dataIndex: 'BIN',
        key: 'BIN',
        align: 'center',
        ellipsis: true,
        width: 150,
    },
    {
        title: 'STR_LOGIN',
        dataIndex: 'STR_LOGIN',
        key: 'STR_LOGIN',
        align: 'center',
        ellipsis: true,
        width: 150,
    },
    {
        title: 'STR_PASS',
        dataIndex: 'STR_PASS',
        key: 'STR_PASS',
        align: 'center',
        ellipsis: true,
        width: 150,
    },
]